<a href="https://colab.research.google.com/github/devbhise/Dictionary/blob/master/deep_learning%20car%20price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ANN



Car Price Prediction


In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("/content/CarPricesData.csv")

In [5]:
df.head()

Age     KM  Weight  HP  MetColor      CC  Doors  Price
0  23.0  46986  1165.0  90         1  2000.0      3  13500
1  23.0  72937  1165.0  90         1  2000.0      3  13750
2  24.0  41711  1165.0  90         1  2000.0      3  13950
3  26.0  48000  1165.0  90         0  2000.0      3  14950
4  30.0  38500  1170.0  90         0  2000.0      3  13750

In [6]:
x = df.iloc[:,:7].values

In [7]:
y = df.iloc[:,7:].values

In [8]:
x

array([[2.3000e+01, 4.6986e+04, 1.1650e+03, ..., 1.0000e+00, 2.0000e+03,
        3.0000e+00],
       [2.3000e+01, 7.2937e+04, 1.1650e+03, ..., 1.0000e+00, 2.0000e+03,
        3.0000e+00],
       [2.4000e+01, 4.1711e+04, 1.1650e+03, ..., 1.0000e+00, 2.0000e+03,
        3.0000e+00],
       ...,
       [7.1000e+01, 1.7016e+04, 1.0150e+03, ..., 0.0000e+00, 1.3000e+03,
        3.0000e+00],
       [7.0000e+01, 1.6916e+04, 1.0150e+03, ..., 1.0000e+00, 1.3000e+03,
        3.0000e+00],
       [7.6000e+01, 1.0000e+00, 1.1140e+03, ..., 0.0000e+00, 1.6000e+03,
        5.0000e+00]])

In [9]:
y.shape

(1435, 1)

In [10]:
x.shape

(1435, 7)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
sc_x = StandardScaler()
sc_y = StandardScaler()

In [13]:
x = sc_x.fit_transform(x)

In [14]:
y = sc_y.fit_transform(y)

In [15]:
x

array([[-1.78270076, -0.57595832,  1.95796873, ...,  0.69457758,
         2.32062178, -1.08444302],
       [-1.78270076,  0.11647404,  1.95796873, ...,  0.69457758,
         2.32062178, -1.08444302],
       [-1.72872398, -0.71670745,  1.95796873, ...,  0.69457758,
         2.32062178, -1.08444302],
       ...,
       [ 0.80818476, -1.37562683, -1.18853963, ..., -1.43972398,
        -1.42866784, -1.08444302],
       [ 0.75420798, -1.37829506, -1.18853963, ...,  0.69457758,
        -1.42866784, -1.08444302],
       [ 1.07806867, -1.82962616,  0.88815589, ..., -1.43972398,
         0.17817057,  1.01565918]])

In [16]:
y

array([[ 0.77036821],
       [ 0.83966875],
       [ 0.89510918],
       ...,
       [-0.61564265],
       [-0.96214536],
       [-1.04530601]])

In [17]:
#split into training and test test

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train , x_test , y_train , y_test = train_test_split(x,y , random_state=0, test_size = 0.30)

Model Training in ANN

In [20]:
from keras.models import Sequential
from keras.layers import Dense

In [21]:
model = Sequential()

In [22]:
#input layer ,hiden layer 2
model.add(Dense(units = 7,activation="relu"))


In [23]:
model.add(Dense(units = 7, activation="linear"))

In [24]:
# output layer
model.add(Dense(units = 1 , activation="linear"))

In [25]:
#Compiling the model

In [26]:
model.compile(loss = "mean_squared_error",optimizer="adam")

In [27]:
#training the model
model.fit(x_train,y_train,batch_size=50,epochs=500,verbose=1)

Epoch 1/500
21/21 [==============================] - 1s 3ms/step - loss: 1.0375
Epoch 2/500
21/21 [==============================] - 0s 2ms/step - loss: 0.7060
Epoch 3/500
21/21 [==============================] - 0s 2ms/step - loss: 0.5134
Epoch 4/500
21/21 [==============================] - 0s 3ms/step - loss: 0.3845
Epoch 5/500
21/21 [==============================] - 0s 2ms/step - loss: 0.3057
Epoch 6/500
21/21 [==============================] - 0s 2ms/step - loss: 0.2544
Epoch 7/500
21/21 [==============================] - 0s 2ms/step - loss: 0.2289
Epoch 8/500
21/21 [==============================] - 0s 2ms/step - loss: 0.2143
Epoch 9/500
21/21 [==============================] - 0s 2ms/step - loss: 0.2053
Epoch 10/500
21/21 [==============================] - 0s 2ms/step - loss: 0.1990
Epoch 11/500
21/21 [==============================] - 0s 3ms/step - loss: 0.1961
Epoch 12/500
21/21 [==============================] - 0s 3ms/step - loss: 0.1884
Epoch 13/500
21/21 [=================

In [28]:
y_predict = model.predict(x_test)

14/14 [==============================] - 1s 4ms/step


In [29]:
y_predict[:10]

array([[-5.7658434e-01],
       [-8.9469329e-02],
       [ 2.9907227e-01],
       [-8.1779802e-01],
       [-2.2176668e-01],
       [-4.9161854e-01],
       [-1.1042159e+00],
       [ 1.4835968e+00],
       [ 1.3772599e-02],
       [-9.9705905e-04]], dtype=float32)

In [30]:
from sklearn.metrics import r2_score,mean_squared_error

In [31]:
r2_score(y_test,y_predict)

0.893690781603604

In [32]:
mean_squared_error(y_test,y_predict)

0.09015956191499558

In [33]:
y_predict[:10],y_test[:10]

(array([[-5.7658434e-01],
        [-8.9469329e-02],
        [ 2.9907227e-01],
        [-8.1779802e-01],
        [-2.2176668e-01],
        [-4.9161854e-01],
        [-1.1042159e+00],
        [ 1.4835968e+00],
        [ 1.3772599e-02],
        [-9.9705905e-04]], dtype=float32),
 array([[-0.35230058],
        [-0.49090167],
        [ 0.34070484],
        [-0.89284482],
        [-0.33844048],
        [-0.40774102],
        [-1.04530601],
        [ 1.39407309],
        [ 0.89510918],
        [-0.06123831]]))

In [34]:
sc_y.inverse_transform(y_test)[:10]

array([[ 9450.],
       [ 8950.],
       [11950.],
       [ 7500.],
       [ 9500.],
       [ 9250.],
       [ 6950.],
       [15750.],
       [13950.],
       [10500.]])

In [35]:
sc_y.inverse_transform(y_predict)[:10]

array([[ 8640.901 ],
       [10398.157 ],
       [11799.812 ],
       [ 7770.7295],
       [ 9920.897 ],
       [ 8947.414 ],
       [ 6737.4844],
       [16072.955 ],
       [10770.6   ],
       [10717.318 ]], dtype=float32)

In [36]:
df = pd.read_csv("/content/Churn_Modelling.csv")

In [37]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [38]:
df.drop("RowNumber",axis = 1,inplace = True)

In [39]:
df.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
0    15634602  Hargrave          619    France  Female   42       2   
1    15647311      Hill          608     Spain  Female   41       1   
2    15619304      Onio          502    France  Female   42       8   
3    15701354      Boni          699    France  Female   39       1   
4    15737888  Mitchell          850     Spain  Female   43       2   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
2  159660.80              3          1               0        113931.57   
3       0.00              2          0               0         93826.63   
4  125510.82              1          1               1         79084.10   

   Exited  
0       1  
1       0  
2       1  
3       0  
4       0

In [40]:
df.drop(["CustomerId","Surname"],axis =1 ,inplace = True)

In [41]:
df.tail()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0

In [42]:
from sklearn.preprocessing import LabelEncoder

In [43]:
le = LabelEncoder()

In [44]:
temp = ["Geography","Gender"]
df.shape

(10000, 11)

In [45]:
for i in temp:
  df[i] = le.fit_transform(df[i])

In [46]:
df.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [47]:
x = df.iloc[:,:-1].values

In [48]:
x[:10]

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, 4.2000000e+01,
        2.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [6.0800000e+02, 2.0000000e+00, 0.0000000e+00, 4.1000000e+01,
        1.0000000e+00, 8.3807860e+04, 1.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [5.0200000e+02, 0.0000000e+00, 0.0000000e+00, 4.2000000e+01,
        8.0000000e+00, 1.5966080e+05, 3.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       [6.9900000e+02, 0.0000000e+00, 0.0000000e+00, 3.9000000e+01,
        1.0000000e+00, 0.0000000e+00, 2.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 9.3826630e+04],
       [8.5000000e+02, 2.0000000e+00, 0.0000000e+00, 4.3000000e+01,
        2.0000000e+00, 1.2551082e+05, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 7.9084100e+04],
       [6.4500000e+02, 2.0000000e+00, 1.0000000e+00, 4.4000000e+01,
        8.0000000e+00, 1.1375578e+05, 2.0000000e+00, 1.00

In [49]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [50]:
y = df.iloc[:,-1:].values

In [51]:
y[:10]

array([[1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0]])

In [52]:
from sklearn.preprocessing import StandardScaler

In [53]:
Sc = StandardScaler()

In [54]:
x = Sc.fit_transform(x)

In [55]:
x.shape

(10000, 10)

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
x_train , x_test , y_train , y_test = train_test_split(x,y, random_state = 0 , test_size = .30)

In [58]:
from keras import Sequential
from keras.layers import Dense

In [84]:
model = Sequential()

In [85]:
model.add(Dense(units = 10 , activation = "relu"))

In [86]:
model.add(Dense(units = 10 , activation = "relu"))

In [87]:
model.add(Dense(units= 5 , activation ="relu"))

In [88]:
model.add(Dense(units = 1 ,activation = "sigmoid"))

In [89]:
from numpy.matrixlib.defmatrix import matrix
model.compile(loss = "binary_crossentropy",optimizer = "adam",metrics=["accuracy"])

In [90]:
test_model = model.fit(x_train,y_train,batch_size=20,epochs=100,callbacks=early_stoping)

Epoch 1/100
350/350 [==============================] - 2s 2ms/step - loss: 0.5139 - accuracy: 0.7740
Epoch 2/100
350/350 [==============================] - 1s 2ms/step - loss: 0.4322 - accuracy: 0.8007
Epoch 3/100
350/350 [==============================] - 1s 2ms/step - loss: 0.4125 - accuracy: 0.8146
Epoch 4/100
350/350 [==============================] - 1s 2ms/step - loss: 0.3918 - accuracy: 0.8286
Epoch 5/100
350/350 [==============================] - 1s 2ms/step - loss: 0.3724 - accuracy: 0.8467
Epoch 6/100
350/350 [==============================] - 1s 2ms/step - loss: 0.3614 - accuracy: 0.8520
Epoch 7/100
350/350 [==============================] - 1s 2ms/step - loss: 0.3550 - accuracy: 0.8521
Epoch 8/100
350/350 [==============================] - 1s 2ms/step - loss: 0.3515 - accuracy: 0.8556
Epoch 9/100
350/350 [==============================] - 1s 2ms/step - loss: 0.3497 - accuracy: 0.8564
Epoch 10/100
350/350 [==============================] - 1s 3ms/step - loss: 0.3476 - accura

In [91]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [92]:
pred = model.predict(x_test)




94/94 [==============================] - 0s 2ms/step


In [93]:
for i in range(len(pred)):
  for j in range(len(pred[i])):
    if pred[i][j] < 0.5:
      pred[i][j] = 0
    else:
      pred[i][j] = 1


In [94]:
accuracy_score(y_test,pred)

0.8553333333333333

In [95]:
y_test[:10]

array([[0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1]])

In [96]:
pred[:10]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [97]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.88      0.94      0.91      2379
           1       0.70      0.53      0.60       621

    accuracy                           0.86      3000
   macro avg       0.79      0.74      0.76      3000
weighted avg       0.85      0.86      0.85      3000



In [98]:
import tensorflow as tf

In [99]:
early_stoping =  tf.keras.callbacks.EarlyStopping(
    monitor="accuracy",min_delta=0.0001,
    patience=10
)

In [100]:
confusion_matrix(y_test,pred)

array([[2236,  143],
       [ 291,  330]])

In [105]:
model.get_weights()

[array([[ 0.02760268, -0.34437928,  0.01393847,  0.09057597, -0.05961185,
         -0.05192663,  0.01435261,  0.16041598,  0.05931251,  0.00580062],
        [-0.32475182,  0.3084602 , -0.37209386,  0.10902964, -1.1913928 ,
         -0.07419135, -0.04561429, -0.29689887,  0.01238722,  0.9426774 ],
        [-0.25408596, -0.4409222 ,  0.41978636,  0.13641214, -0.12539965,
         -0.04408631,  0.6491993 ,  0.09246933,  0.09028352, -0.15542409],
        [ 0.8210459 , -0.5643888 ,  0.12515482, -0.48091456,  0.10963145,
          0.19625644, -0.57237667, -0.60595447,  1.040861  , -0.13966142],
        [ 0.18964344, -0.34497178, -0.92001534, -0.00418201,  0.15703978,
         -0.2608504 ,  0.00204484, -0.34295782, -0.14762492,  0.25700426],
        [-0.06913631,  0.46559334, -0.901945  , -0.38392717,  0.13311312,
          0.6790076 ,  0.18399863, -0.04169381, -0.09970082,  0.10418523],
        [-0.7016494 ,  0.13050883, -0.20667471,  1.1357727 ,  0.15249938,
          0.8636183 ,  0.3132506